

#define NUM_COUNTERS_POWER8 8

static RegisterMap power8_counter_map[NUM_COUNTERS_POWER8] = {
    {"PMC0", PMC0, PMC, IBM_MMCR1, IBM_PMC0, 0, 0, EVENT_OPTION_NONE_MASK},
    {"PMC1", PMC1, PMC, IBM_MMCR1, IBM_PMC1, 0, 0, EVENT_OPTION_NONE_MASK},
    {"PMC2", PMC2, PMC, IBM_MMCR1, IBM_PMC2, 0, 0, EVENT_OPTION_NONE_MASK},
    {"PMC3", PMC3, PMC, IBM_MMCR1, IBM_PMC3, 0, 0, EVENT_OPTION_NONE_MASK},
    {"PMC4", PMC4, PMC, IBM_MMCR1, IBM_PMC4, 0, 0, EVENT_OPTION_NONE_MASK},
    {"PMC5", PMC5, PMC, IBM_MMCR1, IBM_PMC5, 0, 0, EVENT_OPTION_NONE_MASK},
    {"PURR", PMC6, PMC, 0x0, IBM_PURR, 0, 0, EVENT_OPTION_NONE_MASK},
    {"SPURR", PMC7, PMC, 0x0, IBM_SPURR, 0, 0, EVENT_OPTION_NONE_MASK},
};

static BoxMap power8_box_map[NUM_UNITS] = {
    [PMC] = {IBM_MMCR1, 0x0, 0x0, 0, 0, 0, 30},
};
