/* DONT TOUCH: GENERATED FILE! */

#define NUM_ARCH_EVENTS_ATOM 314

static PerfmonEvent  atom_arch_events[NUM_ARCH_EVENTS_ATOM] = {
 {"INSTR_RETIRED_ANY",
  "FIXC0", 
   0x00,0x00}
, {"CPU_CLK_UNHALTED_CORE",
  "FIXC1", 
   0x00,0x00}
, {"BACLEARS_ANY",
  "PMC", 
   0xE6,0x01}
, {"BOGUS_BR",
  "PMC", 
   0xE4,0x01}
, {"BR_INST_RETIRED_ANY",
  "PMC", 
   0xC4,0x00}
, {"BR_INST_RETIRED_PRED_NOT_TAKEN",
  "PMC", 
   0xC4,0x01}
, {"BR_INST_RETIRED_MISPRED_NOT_TAKEN",
  "PMC", 
   0xC4,0x02}
, {"BR_INST_RETIRED_PRED_TAKEN",
  "PMC", 
   0xC4,0x04}
, {"BR_INST_RETIRED_MISPRED_TAKEN",
  "PMC", 
   0xC4,0x08}
, {"BR_INST_RETIRED_TAKEN",
  "PMC", 
   0xC4,0x0C}
, {"BR_INST_RETIRED_MISPRED",
  "PMC", 
   0xC5,0x00}
, {"BR_INST_DECODED",
  "PMC", 
   0xE0,0x00}
, {"BUS_BNR_DRV_THIS_A",
  "PMC", 
   0x61,0x00}
, {"BUS_BNR_DRV_ALL_A",
  "PMC", 
   0x61,0x20}
, {"BUS_DATA_RCV_ALL_CORES",
  "PMC", 
   0x64,0xC0}
, {"BUS_DATA_RCV_THIS_CORE",
  "PMC", 
   0x64,0x40}
, {"BUS_DRDY_CLOCKS_THIS_A",
  "PMC", 
   0x62,0x00}
, {"BUS_DRDY_CLOCKS_ALL_A",
  "PMC", 
   0x62,0x20}
, {"BUS_HIT_DRV_THIS_A",
  "PMC", 
   0x7A,0x00}
, {"BUS_HIT_DRV_ALL_A",
  "PMC", 
   0x7A,0x20}
, {"BUS_HITM_DRV",
  "PMC", 
   0x7B,0x00}
, {"BUS_HITM_DRV",
  "PMC", 
   0x7B,0x20}
, {"BUS_IO_WAIT_ALL_CORES",
  "PMC", 
   0x7F,0xC0}
, {"BUS_IO_WAIT_THIS_CORE",
  "PMC", 
   0x7F,0x40}
, {"BUS_LOCK_CLOCKS_ALL_CORES_THIS_A",
  "PMC", 
   0x63,0xC0}
, {"BUS_LOCK_CLOCKS_ALL_CORES_ALL_A",
  "PMC", 
   0x63,0xE0}
, {"BUS_LOCK_CLOCKS_THIS_CORE_THIS_A",
  "PMC", 
   0x63,0x40}
, {"BUS_LOCK_CLOCKS_THIS_CORE_ALL_A",
  "PMC", 
   0x63,0x60}
, {"BUSQ_EMPTY_ALL_CORES",
  "PMC", 
   0x7D,0xC0}
, {"BUSQ_EMPTY_THIS_CORE",
  "PMC", 
   0x7D,0x40}
, {"BUS_REQUEST_OUTSTANDING_ALL_CORES_THIS_A",
  "PMC", 
   0x60,0xC0}
, {"BUS_REQUEST_OUTSTANDING_ALL_CORES_ALL_A",
  "PMC", 
   0x60,0xE0}
, {"BUS_REQUEST_OUTSTANDING_THIS_CORE_THIS_A",
  "PMC", 
   0x60,0x40}
, {"BUS_REQUEST_OUTSTANDING_THIS_CORE_ALL_A",
  "PMC", 
   0x60,0x60}
, {"BUS_TRANS_ANY_ALL_CORES_THIS_A",
  "PMC", 
   0x70,0xC0}
, {"BUS_TRANS_ANY_ALL_CORES_ALL_A",
  "PMC", 
   0x70,0xE0}
, {"BUS_TRANS_ANY_THIS_CORE_THIS_A",
  "PMC", 
   0x70,0x40}
, {"BUS_TRANS_ANY_THIS_CORE_ALL_A",
  "PMC", 
   0x70,0x60}
, {"BUS_TRANS_BRD_ALL_CORES_THIS_A",
  "PMC", 
   0x65,0xC0}
, {"BUS_TRANS_BRD_ALL_CORES_ALL_A",
  "PMC", 
   0x65,0xE0}
, {"BUS_TRANS_BRD_THIS_CORE_THIS_A",
  "PMC", 
   0x65,0x40}
, {"BUS_TRANS_BRD_THIS_CORE_ALL_A",
  "PMC", 
   0x65,0x60}
, {"BUS_TRANS_BURST_ALL_CORES_THIS_A",
  "PMC", 
   0x6E,0xC0}
, {"BUS_TRANS_BURST_ALL_CORES_ALL_A",
  "PMC", 
   0x6E,0xE0}
, {"BUS_TRANS_BURST_THIS_CORE_THIS_A",
  "PMC", 
   0x6E,0x40}
, {"BUS_TRANS_BURST_THIS_CORE_ALL_A",
  "PMC", 
   0x6E,0x60}
, {"BUS_TRANS_DEF_ALL_CORES_THIS_A",
  "PMC", 
   0x6D,0xC0}
, {"BUS_TRANS_DEF_ALL_CORES_ALL_A",
  "PMC", 
   0x6D,0xE0}
, {"BUS_TRANS_DEF_THIS_CORE_THIS_A",
  "PMC", 
   0x6D,0x40}
, {"BUS_TRANS_DEF_THIS_CORE_ALL_A",
  "PMC", 
   0x6D,0x60}
, {"BUS_TRANS_IFETCH_ALL_CORES_THIS_A",
  "PMC", 
   0x68,0xC0}
, {"BUS_TRANS_IFETCH_ALL_CORES_ALL_A",
  "PMC", 
   0x68,0xE0}
, {"BUS_TRANS_IFETCH_THIS_CORE_THIS_A",
  "PMC", 
   0x68,0x40}
, {"BUS_TRANS_IFETCH_THIS_CORE_ALL_A",
  "PMC", 
   0x68,0x60}
, {"BUS_TRANS_INVAL_ALL_CORES_THIS_A",
  "PMC", 
   0x69,0xC0}
, {"BUS_TRANS_INVAL_ALL_CORES_ALL_A",
  "PMC", 
   0x69,0xE0}
, {"BUS_TRANS_INVAL_THIS_CORE_THIS_A",
  "PMC", 
   0x69,0x40}
, {"BUS_TRANS_INVAL_THIS_CORE_ALL_A",
  "PMC", 
   0x69,0x60}
, {"BUS_TRANS_IO_ALL_CORES_THIS_A",
  "PMC", 
   0x6C,0xC0}
, {"BUS_TRANS_IO_ALL_CORES_ALL_A",
  "PMC", 
   0x6C,0xE0}
, {"BUS_TRANS_IO_THIS_CORE_THIS_A",
  "PMC", 
   0x6C,0x40}
, {"BUS_TRANS_IO_THIS_CORE_ALL_A",
  "PMC", 
   0x6C,0x60}
, {"BUS_TRANS_MEM_ALL_CORES_THIS_A",
  "PMC", 
   0x6F,0xC0}
, {"BUS_TRANS_MEM_ALL_CORES_ALL_A",
  "PMC", 
   0x6F,0xE0}
, {"BUS_TRANS_MEM_THIS_CORE_THIS_A",
  "PMC", 
   0x6F,0x40}
, {"BUS_TRANS_MEM_THIS_CORE_ALL_A",
  "PMC", 
   0x6F,0x60}
, {"BUS_TRANS_P_ALL_CORES_THIS_A",
  "PMC", 
   0x6B,0xC0}
, {"BUS_TRANS_P_ALL_CORES_ALL_A",
  "PMC", 
   0x6B,0xE0}
, {"BUS_TRANS_P_THIS_CORE_THIS_A",
  "PMC", 
   0x6B,0x40}
, {"BUS_TRANS_P_THIS_CORE_ALL_A",
  "PMC", 
   0x6B,0x60}
, {"BUS_TRANS_PWR_ALL_CORES_THIS_A",
  "PMC", 
   0x6A,0xC0}
, {"BUS_TRANS_PWR_ALL_CORES_ALL_A",
  "PMC", 
   0x6A,0xE0}
, {"BUS_TRANS_PWR_THIS_CORE_THIS_A",
  "PMC", 
   0x6A,0x40}
, {"BUS_TRANS_PWR_THIS_CORE_ALL_A",
  "PMC", 
   0x6A,0x60}
, {"BUS_TRANS_RFO_ALL_CORES_THIS_A",
  "PMC", 
   0x66,0xC0}
, {"BUS_TRANS_RFO_ALL_CORES_ALL_A",
  "PMC", 
   0x66,0xE0}
, {"BUS_TRANS_RFO_THIS_CORE_THIS_A",
  "PMC", 
   0x66,0x40}
, {"BUS_TRANS_RFO_THIS_CORE_ALL_A",
  "PMC", 
   0x66,0x60}
, {"BUS_TRANS_WB_ALL_CORES_THIS_A",
  "PMC", 
   0x67,0xC0}
, {"BUS_TRANS_WB_ALL_CORES_ALL_A",
  "PMC", 
   0x67,0xE0}
, {"BUS_TRANS_WB_THIS_CORE_THIS_A",
  "PMC", 
   0x67,0x40}
, {"BUS_TRANS_WB_THIS_CORE_ALL_A",
  "PMC", 
   0x67,0x60}
, {"CPU_CLK_UNHALTED_CORE_P",
  "PMC", 
   0x3C,0x00}
, {"CPU_CLK_UNHALTED_BUS",
  "PMC", 
   0x3C,0x01}
, {"CPU_CLK_UNHALTED_NO_OTHER",
  "PMC", 
   0x3C,0x02}
, {"CYCLES_DIV_BUSY",
  "PMC0", 
   0x14,0x00}
, {"CYCLES_INT_MASKED_CYCLES_INT_MASKED",
  "PMC", 
   0xC6,0x01}
, {"CYCLES_INT_MASKED_CYCLES_INT_PENDING_AND_MASKED",
  "PMC", 
   0xC6,0x02}
, {"DATA_TLB_MISSES_DTLB_MISS",
  "PMC", 
   0x08,0x07}
, {"DIV_AR",
  "PMC", 
   0x13,0x81}
, {"DIV_S",
  "PMC", 
   0x13,0x01}
, {"EIST_TRANS",
  "PMC", 
   0x3A,0x00}
, {"EXT_SNOOP_ALL_CORES_MODIFIED",
  "PMC", 
   0x77,0xC8}
, {"EXT_SNOOP_ALL_CORES_EXCLUSIVE",
  "PMC", 
   0x77,0xC4}
, {"EXT_SNOOP_ALL_CORES_SHARED",
  "PMC", 
   0x77,0xC2}
, {"EXT_SNOOP_ALL_CORES_INVALID",
  "PMC", 
   0x77,0xC1}
, {"EXT_SNOOP_ALL_CORES_MESI",
  "PMC", 
   0x77,0xCF}
, {"EXT_SNOOP_THIS_CORE_MODIFIED",
  "PMC", 
   0x77,0x48}
, {"EXT_SNOOP_THIS_CORE_EXCLUSIVE",
  "PMC", 
   0x77,0x44}
, {"EXT_SNOOP_THIS_CORE_SHARED",
  "PMC", 
   0x77,0x42}
, {"EXT_SNOOP_THIS_CORE_INVALID",
  "PMC", 
   0x77,0x41}
, {"EXT_SNOOP_THIS_CORE_MESI",
  "PMC", 
   0x77,0x4F}
, {"FP_ASSIST",
  "PMC", 
   0x11,0x01}
, {"FP_ASSIST_AR",
  "PMC", 
   0x11,0x81}
, {"HW_INT_RCV",
  "PMC", 
   0xC8,0x00}
, {"ICACHE_ACCESSES",
  "PMC", 
   0x80,0x03}
, {"ICACHE_MISSES",
  "PMC", 
   0x80,0x02}
, {"INST_RETIRED_ANY_P",
  "PMC", 
   0xC0,0x00}
, {"ITLB_MISSES",
  "PMC", 
   0x82,0x02}
, {"ITLB_FLUSH",
  "PMC", 
   0x82,0x04}
, {"L1D_CACHE_LD",
  "PMC", 
   0x40,0x21}
, {"L1D_CACHE_ST",
  "PMC", 
   0x40,0x22}
, {"L2_ADS_ALL_CORES",
  "PMC", 
   0x21,0xC0}
, {"L2_ADS_THIS_CORE",
  "PMC", 
   0x21,0x40}
, {"L2_DBUS_BUSY_CORES_ALL",
  "PMC", 
   0x22,0xC0}
, {"L2_DBUS_BUSY_THIS_CORE",
  "PMC", 
   0x22,0x40}
, {"L2_IFETCH_ALL_CORES_MODIFIED",
  "PMC", 
   0x28,0xC8}
, {"L2_IFETCH_ALL_CORES_EXCLUSIVE",
  "PMC", 
   0x28,0xC4}
, {"L2_IFETCH_ALL_CORES_SHARED",
  "PMC", 
   0x28,0xC2}
, {"L2_IFETCH_ALL_CORES_INVALID",
  "PMC", 
   0x28,0xC1}
, {"L2_IFETCH_ALL_CORES_MESI",
  "PMC", 
   0x28,0xCF}
, {"L2_IFETCH_THIS_CORE_MODIFIED",
  "PMC", 
   0x28,0x48}
, {"L2_IFETCH_THIS_CORE_EXCLUSIVE",
  "PMC", 
   0x28,0x44}
, {"L2_IFETCH_THIS_CORE_SHARED",
  "PMC", 
   0x28,0x42}
, {"L2_IFETCH_THIS_CORE_INVALID",
  "PMC", 
   0x28,0x41}
, {"L2_IFETCH_THIS_CORE_MESI",
  "PMC", 
   0x28,0x4F}
, {"L2_LD_ALL_CORES_ALL_MODIFIED",
  "PMC", 
   0x29,0xF8}
, {"L2_LD_ALL_CORES_ALL_EXCLUSIVE",
  "PMC", 
   0x29,0xF4}
, {"L2_LD_ALL_CORES_ALL_SHARED",
  "PMC", 
   0x29,0xF2}
, {"L2_LD_ALL_CORES_ALL_INVALID",
  "PMC", 
   0x29,0xF1}
, {"L2_LD_ALL_CORES_ALL_MESI",
  "PMC", 
   0x29,0xFF}
, {"L2_LD_THIS_CORE_ALL_MODIFIED",
  "PMC", 
   0x29,0x78}
, {"L2_LD_THIS_CORE_ALL_EXCLUSIVE",
  "PMC", 
   0x29,0x74}
, {"L2_LD_THIS_CORE_ALL_SHARED",
  "PMC", 
   0x29,0x72}
, {"L2_LD_THIS_CORE_ALL_INVALID",
  "PMC", 
   0x29,0x71}
, {"L2_LD_THIS_CORE_ALL_MESI",
  "PMC", 
   0x29,0x7F}
, {"L2_LD_ALL_CORES_PREFETCH_ONLY_MODIFIED",
  "PMC", 
   0x29,0xD8}
, {"L2_LD_ALL_CORES_PREFETCH_ONLY_EXCLUSIVE",
  "PMC", 
   0x29,0xD4}
, {"L2_LD_ALL_CORES_PREFETCH_ONLY_SHARED",
  "PMC", 
   0x29,0xD2}
, {"L2_LD_ALL_CORES_PREFETCH_ONLY_INVALID",
  "PMC", 
   0x29,0xD1}
, {"L2_LD_ALL_CORES_PREFETCH_ONLY_MESI",
  "PMC", 
   0x29,0xDF}
, {"L2_LD_THIS_CORE_PREFETCH_ONLY_MODIFIED",
  "PMC", 
   0x29,0x58}
, {"L2_LD_THIS_CORE_PREFETCH_ONLY_EXCLUSIVE",
  "PMC", 
   0x29,0x54}
, {"L2_LD_THIS_CORE_PREFETCH_ONLY_SHARED",
  "PMC", 
   0x29,0x52}
, {"L2_LD_THIS_CORE_PREFETCH_ONLY_INVALID",
  "PMC", 
   0x29,0x51}
, {"L2_LD_THIS_CORE_PREFETCH_ONLY_MESI",
  "PMC", 
   0x29,0x5F}
, {"L2_LD_ALL_CORES_NO_PREFETCH_MODIFIED",
  "PMC", 
   0x29,0xC8}
, {"L2_LD_ALL_CORES_NO_PREFETCH_EXCLUSIVE",
  "PMC", 
   0x29,0xC4}
, {"L2_LD_ALL_CORES_NO_PREFETCH_SHARED",
  "PMC", 
   0x29,0xC2}
, {"L2_LD_ALL_CORES_NO_PREFETCH_INVALID",
  "PMC", 
   0x29,0xC1}
, {"L2_LD_ALL_CORES_NO_PREFETCH_MESI",
  "PMC", 
   0x29,0xCF}
, {"L2_LD_THIS_CORE_NO_PREFETCH_MODIFIED",
  "PMC", 
   0x29,0x48}
, {"L2_LD_THIS_CORE_NO_PREFETCH_EXCLUSIVE",
  "PMC", 
   0x29,0x44}
, {"L2_LD_THIS_CORE_NO_PREFETCH_SHARED",
  "PMC", 
   0x29,0x42}
, {"L2_LD_THIS_CORE_NO_PREFETCH_INVALID",
  "PMC", 
   0x29,0x41}
, {"L2_LD_THIS_CORE_NO_PREFETCH_MESI",
  "PMC", 
   0x29,0x4F}
, {"L2_LINES_IN_ALL_CORES_ALL",
  "PMC", 
   0x24,0xF0}
, {"L2_LINES_IN_THIS_CORE_ALL",
  "PMC", 
   0x24,0x70}
, {"L2_LINES_IN_ALL_CORES_PREFETCH_ONLY",
  "PMC", 
   0x24,0xD0}
, {"L2_LINES_IN_THIS_CORE_PREFETCH_ONLY",
  "PMC", 
   0x24,0x50}
, {"L2_LINES_IN_ALL_CORES_NO_PREFETCH",
  "PMC", 
   0x24,0xC0}
, {"L2_LINES_IN_THIS_CORE_NO_PREFETCH",
  "PMC", 
   0x24,0x40}
, {"L2_LINES_OUT_ALL_CORES_ALL",
  "PMC", 
   0x26,0xF0}
, {"L2_LINES_OUT_THIS_CORE_ALL",
  "PMC", 
   0x26,0x70}
, {"L2_LINES_OUT_ALL_CORES_PREFETCH_ONLY",
  "PMC", 
   0x26,0xD0}
, {"L2_LINES_OUT_THIS_CORE_PREFETCH_ONLY",
  "PMC", 
   0x26,0x50}
, {"L2_LINES_OUT_ALL_CORES_NO_PREFETCH",
  "PMC", 
   0x26,0xC0}
, {"L2_LINES_OUT_THIS_CORE_NO_PREFETCH",
  "PMC", 
   0x26,0x40}
, {"L2_LOCK_ALL_CORES_MODIFIED",
  "PMC", 
   0x2B,0xC8}
, {"L2_LOCK_ALL_CORES_EXCLUSIVE",
  "PMC", 
   0x2B,0xC4}
, {"L2_LOCK_ALL_CORES_SHARED",
  "PMC", 
   0x2B,0xC2}
, {"L2_LOCK_ALL_CORES_INVALID",
  "PMC", 
   0x2B,0xC1}
, {"L2_LOCK_ALL_CORES_MESI",
  "PMC", 
   0x2B,0xCF}
, {"L2_LOCK_THIS_CORE_MODIFIED",
  "PMC", 
   0x2B,0x48}
, {"L2_LOCK_THIS_CORE_EXCLUSIVE",
  "PMC", 
   0x2B,0x44}
, {"L2_LOCK_THIS_CORE_SHARED",
  "PMC", 
   0x2B,0x42}
, {"L2_LOCK_THIS_CORE_INVALID",
  "PMC", 
   0x2B,0x41}
, {"L2_LOCK_THIS_CORE_MESI",
  "PMC", 
   0x2B,0x4F}
, {"L2_M_LINES_IN_ALL_CORES",
  "PMC", 
   0x25,0xC0}
, {"L2_M_LINES_IN_THIS_CORE",
  "PMC", 
   0x25,0x40}
, {"L2_M_LINES_OUT_ALL_CORES_ALL",
  "PMC", 
   0x27,0xF0}
, {"L2_M_LINES_OUT_THIS_CORE_ALL",
  "PMC", 
   0x27,0x70}
, {"L2_M_LINES_OUT_ALL_CORES_PREFETCH_ONLY",
  "PMC", 
   0x27,0xD0}
, {"L2_M_LINES_OUT_THIS_CORE_PREFETCH_ONLY",
  "PMC", 
   0x27,0x50}
, {"L2_M_LINES_OUT_ALL_CORES_NO_PREFETCH",
  "PMC", 
   0x27,0xC0}
, {"L2_M_LINES_OUT_THIS_CORE_NO_PREFETCH",
  "PMC", 
   0x27,0x40}
, {"L2_NO_REQ_ALL_CORES",
  "PMC", 
   0x32,0xC0}
, {"L2_NO_REQ_THIS_CORE",
  "PMC", 
   0x32,0x40}
, {"L2_REJECT_BUSQ_ALL_CORES_ALL_MODIFIED",
  "PMC", 
   0x30,0xF8}
, {"L2_REJECT_BUSQ_ALL_CORES_ALL_EXCLUSIVE",
  "PMC", 
   0x30,0xF4}
, {"L2_REJECT_BUSQ_ALL_CORES_ALL_SHARED",
  "PMC", 
   0x30,0xF2}
, {"L2_REJECT_BUSQ_ALL_CORES_ALL_INVALID",
  "PMC", 
   0x30,0xF1}
, {"L2_REJECT_BUSQ_ALL_CORES_ALL_MESI",
  "PMC", 
   0x30,0xFF}
, {"L2_REJECT_BUSQ_THIS_CORE_ALL_MODIFIED",
  "PMC", 
   0x30,0x78}
, {"L2_REJECT_BUSQ_THIS_CORE_ALL_EXCLUSIVE",
  "PMC", 
   0x30,0x74}
, {"L2_REJECT_BUSQ_THIS_CORE_ALL_SHARED",
  "PMC", 
   0x30,0x72}
, {"L2_REJECT_BUSQ_THIS_CORE_ALL_INVALID",
  "PMC", 
   0x30,0x71}
, {"L2_REJECT_BUSQ_THIS_CORE_ALL_MESI",
  "PMC", 
   0x30,0x7F}
, {"L2_REJECT_BUSQ_ALL_CORES_PREFETCH_ONLY_MODIFIED",
  "PMC", 
   0x30,0xD8}
, {"L2_REJECT_BUSQ_ALL_CORES_PREFETCH_ONLY_EXCLUSIVE",
  "PMC", 
   0x30,0xD4}
, {"L2_REJECT_BUSQ_ALL_CORES_PREFETCH_ONLY_SHARED",
  "PMC", 
   0x30,0xD2}
, {"L2_REJECT_BUSQ_ALL_CORES_PREFETCH_ONLY_INVALID",
  "PMC", 
   0x30,0xD1}
, {"L2_REJECT_BUSQ_ALL_CORES_PREFETCH_ONLY_MESI",
  "PMC", 
   0x30,0xDF}
, {"L2_REJECT_BUSQ_THIS_CORE_PREFETCH_ONLY_MODIFIED",
  "PMC", 
   0x30,0x58}
, {"L2_REJECT_BUSQ_THIS_CORE_PREFETCH_ONLY_EXCLUSIVE",
  "PMC", 
   0x30,0x54}
, {"L2_REJECT_BUSQ_THIS_CORE_PREFETCH_ONLY_SHARED",
  "PMC", 
   0x30,0x52}
, {"L2_REJECT_BUSQ_THIS_CORE_PREFETCH_ONLY_INVALID",
  "PMC", 
   0x30,0x51}
, {"L2_REJECT_BUSQ_THIS_CORE_PREFETCH_ONLY_MESI",
  "PMC", 
   0x30,0x5F}
, {"L2_REJECT_BUSQ_ALL_CORES_NO_PREFETCH_MODIFIED",
  "PMC", 
   0x30,0xC8}
, {"L2_REJECT_BUSQ_ALL_CORES_NO_PREFETCH_EXCLUSIVE",
  "PMC", 
   0x30,0xC4}
, {"L2_REJECT_BUSQ_ALL_CORES_NO_PREFETCH_SHARED",
  "PMC", 
   0x30,0xC2}
, {"L2_REJECT_BUSQ_ALL_CORES_NO_PREFETCH_INVALID",
  "PMC", 
   0x30,0xC1}
, {"L2_REJECT_BUSQ_ALL_CORES_NO_PREFETCH_MESI",
  "PMC", 
   0x30,0xCF}
, {"L2_REJECT_BUSQ_THIS_CORE_NO_PREFETCH_MODIFIED",
  "PMC", 
   0x30,0x48}
, {"L2_REJECT_BUSQ_THIS_CORE_NO_PREFETCH_EXCLUSIVE",
  "PMC", 
   0x30,0x44}
, {"L2_REJECT_BUSQ_THIS_CORE_NO_PREFETCH_SHARED",
  "PMC", 
   0x30,0x42}
, {"L2_REJECT_BUSQ_THIS_CORE_NO_PREFETCH_INVALID",
  "PMC", 
   0x30,0x41}
, {"L2_REJECT_BUSQ_THIS_CORE_NO_PREFETCH_MESI",
  "PMC", 
   0x30,0x4F}
, {"L2_RQSTS_ALL_CORES_ALL_MODIFIED",
  "PMC", 
   0x2E,0xF8}
, {"L2_RQSTS_ALL_CORES_ALL_EXCLUSIVE",
  "PMC", 
   0x2E,0xF4}
, {"L2_RQSTS_ALL_CORES_ALL_SHARED",
  "PMC", 
   0x2E,0xF2}
, {"L2_RQSTS_ALL_CORES_ALL_INVALID",
  "PMC", 
   0x2E,0xF1}
, {"L2_RQSTS_ALL_CORES_ALL_MESI",
  "PMC", 
   0x2E,0xFF}
, {"L2_RQSTS_THIS_CORE_ALL_MODIFIED",
  "PMC", 
   0x2E,0x78}
, {"L2_RQSTS_THIS_CORE_ALL_EXCLUSIVE",
  "PMC", 
   0x2E,0x74}
, {"L2_RQSTS_THIS_CORE_ALL_SHARED",
  "PMC", 
   0x2E,0x72}
, {"L2_RQSTS_THIS_CORE_ALL_INVALID",
  "PMC", 
   0x2E,0x71}
, {"L2_RQSTS_THIS_CORE_ALL_MESI",
  "PMC", 
   0x2E,0x7F}
, {"L2_RQSTS_ALL_CORES_PREFETCH_ONLY_MODIFIED",
  "PMC", 
   0x2E,0xD8}
, {"L2_RQSTS_ALL_CORES_PREFETCH_ONLY_EXCLUSIVE",
  "PMC", 
   0x2E,0xD4}
, {"L2_RQSTS_ALL_CORES_PREFETCH_ONLY_SHARED",
  "PMC", 
   0x2E,0xD2}
, {"L2_RQSTS_ALL_CORES_PREFETCH_ONLY_INVALID",
  "PMC", 
   0x2E,0xD1}
, {"L2_RQSTS_ALL_CORES_PREFETCH_ONLY_MESI",
  "PMC", 
   0x2E,0xDF}
, {"L2_RQSTS_THIS_CORE_PREFETCH_ONLY_MODIFIED",
  "PMC", 
   0x2E,0x58}
, {"L2_RQSTS_THIS_CORE_PREFETCH_ONLY_EXCLUSIVE",
  "PMC", 
   0x2E,0x54}
, {"L2_RQSTS_THIS_CORE_PREFETCH_ONLY_SHARED",
  "PMC", 
   0x2E,0x52}
, {"L2_RQSTS_THIS_CORE_PREFETCH_ONLY_INVALID",
  "PMC", 
   0x2E,0x51}
, {"L2_RQSTS_THIS_CORE_PREFETCH_ONLY_MESI",
  "PMC", 
   0x2E,0x5F}
, {"L2_RQSTS_ALL_CORES_NO_PREFETCH_MODIFIED",
  "PMC", 
   0x2E,0xC8}
, {"L2_RQSTS_ALL_CORES_NO_PREFETCH_EXCLUSIVE",
  "PMC", 
   0x2E,0xC4}
, {"L2_RQSTS_ALL_CORES_NO_PREFETCH_SHARED",
  "PMC", 
   0x2E,0xC2}
, {"L2_RQSTS_ALL_CORES_NO_PREFETCH_INVALID",
  "PMC", 
   0x2E,0xC1}
, {"L2_RQSTS_ALL_CORES_NO_PREFETCH_MESI",
  "PMC", 
   0x2E,0xCF}
, {"L2_RQSTS_THIS_CORE_NO_PREFETCH_MODIFIED",
  "PMC", 
   0x2E,0x48}
, {"L2_RQSTS_THIS_CORE_NO_PREFETCH_EXCLUSIVE",
  "PMC", 
   0x2E,0x44}
, {"L2_RQSTS_THIS_CORE_NO_PREFETCH_SHARED",
  "PMC", 
   0x2E,0x42}
, {"L2_RQSTS_SELF_I_STATE",
  "PMC", 
   0x2E,0x41}
, {"L2_RQSTS_SELF_MESI",
  "PMC", 
   0x2E,0x4F}
, {"L2_ST_ALL_CORES_MODIFIED",
  "PMC", 
   0x2A,0xC8}
, {"L2_ST_ALL_CORES_EXCLUSIVE",
  "PMC", 
   0x2A,0xC4}
, {"L2_ST_ALL_CORES_SHARED",
  "PMC", 
   0x2A,0xC2}
, {"L2_ST_ALL_CORES_INVALID",
  "PMC", 
   0x2A,0xC1}
, {"L2_ST_ALL_CORES_MESI",
  "PMC", 
   0x2A,0xCF}
, {"L2_ST_THIS_CORE_MODIFIED",
  "PMC", 
   0x2A,0x48}
, {"L2_ST_THIS_CORE_EXCLUSIVE",
  "PMC", 
   0x2A,0x44}
, {"L2_ST_THIS_CORE_SHARED",
  "PMC", 
   0x2A,0x42}
, {"L2_ST_THIS_CORE_INVALID",
  "PMC", 
   0x2A,0x41}
, {"L2_ST_THIS_CORE_MESI",
  "PMC", 
   0x2A,0x4F}
, {"MACHINE_CLEARS_SMC",
  "PMC", 
   0xC3,0x01}
, {"MACRO_INSTS_DECODED",
  "PMC", 
   0xAA,0x01}
, {"MACRO_INSTS_CISC_DECODED",
  "PMC", 
   0xAA,0x08}
, {"MEM_LOAD_RETIRED_L1D_MISS",
  "PMC0", 
   0xCB,0x01}
, {"MEM_LOAD_RETIRED_L1D_LINE_MISS",
  "PMC0", 
   0xCB,0x02}
, {"MEM_LOAD_RETIRED_L2_MISS",
  "PMC0", 
   0xCB,0x04}
, {"MEM_LOAD_RETIRED_L2_LINE_MISS",
  "PMC0", 
   0xCB,0x08}
, {"MEM_LOAD_RETIRED_DTLB_MISS",
  "PMC0", 
   0xCB,0x10}
, {"MUL",
  "PMC1", 
   0x12,0x00}
, {"MUL_S",
  "PMC1", 
   0x12,0x01}
, {"MUL_AR",
  "PMC1", 
   0x12,0x81}
, {"PAGE_WALKS_WALKS",
  "PMC", 
   0x0C,0x03}
, {"PAGE_WALKS_CYCLES",
  "PMC", 
   0x0C,0x02}
, {"PREFETCH_PREFETCHNTA",
  "PMC", 
   0x07,0x08}
, {"PREFETCH_PREFETCHT0",
  "PMC", 
   0x07,0x01}
, {"PREFETCH_SW_L2",
  "PMC", 
   0x07,0x06}
, {"SEGMENT_REG_LOADS_ANY",
  "PMC", 
   0x06,0x00}
, {"SIMD_ASSIST",
  "PMC", 
   0xCD,0x00}
, {"SIMD_INSTR_RETIRED",
  "PMC", 
   0xCE,0x00}
, {"SIMD_COMP_INST_RETIRED_PACKED_SINGLE",
  "PMC", 
   0xCA,0x01}
, {"SIMD_COMP_INST_RETIRED_SCALAR_SINGLE",
  "PMC", 
   0xCA,0x02}
, {"SIMD_COMP_INST_RETIRED_PACKED_DOUBLE",
  "PMC", 
   0xCA,0x04}
, {"SIMD_COMP_INST_RETIRED_SCALAR_DOUBLE",
  "PMC", 
   0xCA,0x08}
, {"SIMD_INST_RETIRED_ANY",
  "PMC", 
   0xCA,0x1F}
, {"SIMD_INST_RETIRED_PACKED_SINGLE",
  "PMC", 
   0xC7,0x01}
, {"SIMD_INST_RETIRED_SCALAR_SINGLE",
  "PMC", 
   0xC7,0x02}
, {"SIMD_INST_RETIRED_PACKED_DOUBLE",
  "PMC", 
   0xC7,0x04}
, {"SIMD_INST_RETIRED_SCALAR_DOUBLE",
  "PMC", 
   0xC7,0x08}
, {"SIMD_INST_RETIRED_VECTOR",
  "PMC", 
   0xC7,0x10}
, {"SIMD_INST_RETIRED_ANY",
  "PMC", 
   0xC7,0x1F}
, {"SIMD_SAT_INSTR_RETIRED",
  "PMC", 
   0xCF,0x00}
, {"SIMD_SAT_UOPS_EXEC_S",
  "PMC", 
   0xB1,0x00}
, {"SIMD_SAT_UOP_EXEC_AR",
  "PMC", 
   0xB1,0x80}
, {"SIMD_UOPS_EXEC_S",
  "PMC", 
   0xB0,0x00}
, {"SIMD_UOPS_EXEC_AR",
  "PMC", 
   0xB0,0xB0}
, {"SIMD_UOP_TYPE_EXEC_ARITHMETIC_AR",
  "PMC", 
   0xB3,0xA0}
, {"SIMD_UOP_TYPE_EXEC_ARITHMETIC_S",
  "PMC", 
   0xB3,0x20}
, {"SIMD_UOP_TYPE_EXEC_LOGICAL_AR",
  "PMC", 
   0xB3,0x90}
, {"SIMD_UOP_TYPE_EXEC_LOGICAL_S",
  "PMC", 
   0xB3,0x10}
, {"SIMD_UOP_TYPE_EXEC_MUL_AR",
  "PMC", 
   0xB3,0x81}
, {"SIMD_UOP_TYPE_EXEC_MUL_S",
  "PMC", 
   0xB3,0x01}
, {"SIMD_UOP_TYPE_EXEC_PACK_AR",
  "PMC", 
   0xB3,0x84}
, {"SIMD_UOP_TYPE_EXEC_PACK_S",
  "PMC", 
   0xB3,0x04}
, {"SIMD_UOP_TYPE_EXEC_SHIFT_AR",
  "PMC", 
   0xB3,0x82}
, {"SIMD_UOP_TYPE_EXEC_SHIFT_SSIMD",
  "PMC", 
   0xB3,0x02}
, {"SIMD_UOP_TYPE_EXEC_UNPACK_AR",
  "PMC", 
   0xB3,0x88}
, {"SIMD_UOP_TYPE_EXEC_UNPACK_S",
  "PMC", 
   0xB3,0x08}
, {"SNOOP_STALL_DRV_ALL_CORES_THIS_A",
  "PMC", 
   0x7E,0xC0}
, {"SNOOP_STALL_DRV_ALL_CORES_ALL_A",
  "PMC", 
   0x7E,0xE0}
, {"SNOOP_STALL_DRV_THIS_CORE_THIS_A",
  "PMC", 
   0x7E,0x40}
, {"SNOOP_STALL_DRV_THIS_CORE_ALL_A",
  "PMC", 
   0x7E,0x60}
, {"STORE_FORWARDS_GOOD",
  "PMC", 
   0x02,0x81}
, {"THERMAL_TRIP",
  "PMC", 
   0x3B,0xC0}
, {"UOPS_RETIRED_ANY",
  "PMC", 
   0xC2,0x00}
, {"X87_COMP_OPS_EXE_ANY_S",
  "PMC", 
   0x10,0x01}
, {"X87_COMP_OPS_EXE_ANY_AR",
  "PMC", 
   0x10,0x81}
};
