.TH LIKWID-MEMSWEEPER 1 <DATE> likwid\-<VERSION>
.SH NAME
likwid-memsweeper \- A tool to clean up NUMA memory domains and last level caches.
.SH SYNOPSIS
.B likwid-memsweeper
.RB [\-hv]
.RB [ \-c
.IR <NUMA_ID> ]
.SH DESCRIPTION
.B likwid-memsweeper
is a command line application to shrink the file buffer cache by filling the NUMA domain with random pages. Moreover the tool invalidates all cachelines in the LLC for 64 bit x86 systems. If no NUMA domain is specified, all are sweept.
.SH OPTIONS
.TP
.B \-h
prints a help message to standard output, then exits.
.TP
.B \-v
prints a version message to standard output, then exits.
.TP
.B \-\^c " <NUMA_ID>
set the NUMA domain for sweeping.

.SH AUTHOR
Written by Thomas Roehl <thomas.roehl@gmail.com>.
.SH BUGS
Report Bugs on <http://code.google.com/p/likwid/issues/list>.
.SH "SEE ALSO"
likwid-perfctr(1), likwid-features(1), likwid-pin(1), likwid-powermeter(1), likwid-topology(1),
