.TH LIKWID-POWERMETER 1 <DATE> likwid\-<VERSION>
.SH NAME
likwid-powermeter \- A tool to print Power and Clocking information on Intel CPUS
.SH SYNOPSIS
.B likwid-powermeter 
.RB [ \-vh ]
.RB [ \-c
.IR socketId ]
.RB [ \-s
.IR duration in seconds ]
.SH DESCRIPTION
.B likwid-powermeter
is a command line application to get the Energy comsumption on Intel RAPL capable processors. Currently
only Intel SandyBridge is supported. It also prints information about TDP and Turbo Mode steps supported.
The Turbo Mode information works on all Turbo mode enabled Intel processors. The tool can be either used
in stethoscope mode for a specified duration or as a wrapper to your application measuring your complete 
run. RAPL works on a per package (socket) base.
Please note that the RAPL counters are also accessible as normal events withing likwid-perfctr.
.SH OPTIONS
.TP
.B \-\^v
prints version information to standard output, then exits.
.TP
.B \-\^h
prints a help message to standard output, then exits.
.TP
.B \-\^c " socketId"
set on which socket the RAPL interface is accessed.
.TP
.B \-\^p
prints out information about dynamic clocks and CPI information on the socket measured.
.TP
.B \-\^i
prints out information TDP and Turbo mode steps

.SH AUTHOR
Written by Jan Treibig <jan.treibig@gmail.com>.
.SH BUGS
Report Bugs on <http://code.google.com/p/likwid/issues/list>.
.SH "SEE ALSO"
likwid-topology(1), likwid-perfCtr(1), likwid-pin(1),
