name: LIKWID Build Tests for AMD GPU support

on:
  push:
    branches: [ master ]
    paths:
      - '**/rocmon*'
      - 'src/topology_rocm.c'
      - '**/sysFeatures_amd*'
      - 'src/includes/likwid*.h'
      - 'src/meta.c'
      - 'src/devstring.c'
      - 'src/perfgroup.c'
      - 'src/sysFeatures.c'
      - 'src/likwid_device.c'
      - 'src/affinity.c'
      - 'src/luawid.c'
      - 'src/cpustring.c'
      - '.github/workflows/buildtests-amd.yml'
  pull_request:
    branches: [ master ]
    paths:
      - '**/rocmon*'
      - 'src/topology_rocm.c'
      - '**/sysFeatures_amd*'
      - 'src/includes/likwid*.h'
      - 'src/meta.c'
      - 'src/devstring.c'
      - 'src/perfgroup.c'
      - 'src/sysFeatures.c'
      - 'src/likwid_device.c'
      - 'src/affinity.c'
      - 'src/luawid.c'
      - 'src/cpustring.c'
      - '.github/workflows/buildtests-amd.yml'

jobs:
  build-x86-rocm:
    runs-on: ubuntu-24.04
    container: rocm/dev-ubuntu-24.04:${{matrix.rocm_version}}
    strategy:
      fail-fast: false
      matrix:
        # You can find the available versions here:
        # https://hub.docker.com/r/rocm/dev-ubuntu-24.04/tags
        rocm_version: [ "7.0.2", "7.1.1", "7.2.1" ]
    steps:
    - uses: actions/checkout@v6
    - name: make -j$(nproc)
      run: ROCM_HOME=/opt/rocm make ACCESSMODE=accessdaemon ROCM_INTERFACE=true -j$(nproc)
