name: LIKWID Build Tests

on:
  push:
    branches: [ master, gh-actions-cuda-rocm ]
  pull_request:
    branches: [ master ]

jobs:
  build-x86-accessdaemon:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make accessdaemon
      run: make ACCESSMODE=accessdaemon BUILD_SYSFEATURES=true -j

  build-x86-perfevent:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make perf_event
      run: make ACCESSMODE=perf_event BUILD_SYSFEATURES=true -j
  build-aarch64-perfevent:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v2
    - name: make perf_event
      run: make COMPILER=GCCARM ACCESSMODE=perf_event BUILD_SYSFEATURES=true -j

  build-x86-cuda:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        # You can find the available versions here:
        # https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/
        cuda_version: [ "12-5", "12-6", "12-8", "12-9", "13-0", "13-1" ]
    steps:
    - uses: actions/checkout@v2
    - name: Install CUDA ${{matrix.cuda_version}}
      run: |
        sudo apt update
        sudo apt install wget
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb
        sudo dpkg -i cuda-keyring_1.1-1_all.deb
        sudo apt update
        sudo apt install cuda-toolkit-${{matrix.cuda_version}} cuda-cupti-dev-${{matrix.cuda_version}}
    - name: make -j$(nproc)
      run: CUDA_HOME=/usr/local/cuda make ACCESSMODE=accessdaemon NVIDIA_INTERFACE=true

  build-x86-rocm:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        # You can find the available versions here:
        # https://repo.radeon.com/rocm/apt/
        rocm_version: [ "7.0.3", "7.1.1", "7.2" ]
    steps:
    - uses: actions/checkout@v2
    - name: Install ROCm ${{matrix.rocm_version}}
      run: |
        sudo apt update
        sudo apt install curl gpg
        curl https://repo.radeon.com/rocm/rocm.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/rocm.gpg
        echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/rocm/apt/${{matrix.rocm_version}} noble main" | sudo tee /etc/apt/sources.list.d/rocm.list
        echo -e 'Package: *\nPin: release o=repo.radeon.com\nPin-Priority: 600' | sudo tee /etc/apt/preferences.d/rocm-pin-600
        sudo apt update
        sudo apt install rocm
    - name: make -j$(nproc)
      run: ROCM_HOME=/opt/rocm make ACCESSMODE=accessdaemon ROCM_INTERFACE=true
